const events = [
  {id:1,title:"GenAI Builders: From prompt to prototype",date:"2026-07-17",time:"6:30 PM",venue:"T-Hub, Raidurg",area:"Hitech City",source:"Luma",format:"In person",topics:["AI","Career"],price:"Free",link:"https://lu.ma/",summary:"A hands-on evening for developers shipping their first generative AI prototype. Bring a laptop; beginner-friendly build stations included.",urgency:"REGISTRATION CLOSING"},
  {id:2,title:"AWS User Group Hyderabad — Serverless Night",date:"2026-07-18",time:"10:00 AM",venue:"AWS Office, Nanakramguda",area:"Financial District",source:"Community",format:"In person",topics:["Cloud","AI"],price:"Free",link:"https://aws.amazon.com/events/",summary:"Local AWS builders share practical serverless patterns, followed by an architecture clinic and community networking."},
  {id:3,title:"React Hyderabad: Design systems that scale",date:"2026-07-18",time:"3:00 PM",venue:"91Springboard, Kondapur",area:"Kondapur",source:"Meetup",format:"In person",topics:["Web"],price:"Free",link:"https://www.meetup.com/",summary:"A focused community session on scalable component APIs, accessibility, and practical design-system workflows."},
  {id:4,title:"Google Cloud Study Jam: AI on Vertex",date:"2026-07-19",time:"11:00 AM",venue:"Google for Startups, Madhapur",area:"Madhapur",source:"Community",format:"Hybrid",topics:["AI","Cloud"],price:"Free",link:"https://developers.google.com/events",summary:"Build an AI workflow using Google Cloud services with mentors from the local developer community.",urgency:"THIS WEEKEND"},
  {id:5,title:"Hyderabad Open Source Hacknight",date:"2026-07-21",time:"6:00 PM",venue:"Devfolio Space, Jubilee Hills",area:"Jubilee Hills",source:"Luma",format:"In person",topics:["Web","Career"],price:"Free",link:"https://lu.ma/",summary:"Bring an issue, an idea, or a half-finished project. Pair up with local contributors and ship something useful."},
  {id:6,title:"Microsoft Reactor: Copilot for developers",date:"2026-07-22",time:"5:30 PM",venue:"Microsoft Reactor",area:"Online",source:"Community",format:"Online",topics:["AI","Career"],price:"Free",link:"https://developer.microsoft.com/reactor/",summary:"A live developer session on integrating AI coding assistants into real software delivery workflows."},
  {id:7,title:"Product x Engineering: the 0-to-1 playbook",date:"2026-07-24",time:"7:00 PM",venue:"WeWork, RMZ Futura",area:"Hitech City",source:"Eventbrite",format:"In person",topics:["Career"],price:"₹299",link:"https://www.eventbrite.com/",summary:"A candid panel for early-stage builders on turning customer signals into product decisions and prototypes."},
  {id:8,title:"Flutter Forward Hyderabad",date:"2026-07-25",time:"10:30 AM",venue:"T-Hub, Raidurg",area:"Hitech City",source:"Meetup",format:"In person",topics:["Web"],price:"Free",link:"https://www.meetup.com/",summary:"Talks and live coding on modern Flutter architecture, performance, and shipping for multiple platforms."},
  {id:9,title:"Data & Chai: practical RAG systems",date:"2026-07-26",time:"4:00 PM",venue:"The Garage Society, Gachibowli",area:"Gachibowli",source:"Luma",format:"In person",topics:["AI"],price:"Free",link:"https://lu.ma/",summary:"A small-group technical discussion for data practitioners building retrieval-augmented applications."},
  {id:10,title:"Kubernetes Community Days — Hyderabad",date:"2026-07-28",time:"9:30 AM",venue:"IIIT Hyderabad",area:"Gachibowli",source:"Eventbrite",format:"Hybrid",topics:["Cloud"],price:"Free",link:"https://www.eventbrite.com/",summary:"A day for cloud-native practitioners featuring talks, contributor sessions, and platform engineering workshops."},
  {id:11,title:"Localhost Hyderabad: Build your first API",date:"2026-07-30",time:"2:00 PM",venue:"T-Hub, Raidurg",area:"Hitech City",source:"Community",format:"In person",topics:["Web","Career"],price:"Free",link:"https://localhost.run/",summary:"A beginner-friendly workshop on API fundamentals, deployment, and the developer tools used by local teams."},
  {id:12,title:"Founders & engineers lightning demos",date:"2026-08-02",time:"5:00 PM",venue:"CIE, IIIT Hyderabad",area:"Gachibowli",source:"Meetup",format:"In person",topics:["Career","AI"],price:"Free",link:"https://www.meetup.com/",summary:"Five-minute product demos, useful feedback, and low-pressure networking for people building in Hyderabad."}
];
const state={query:"",date:"all",format:"",topic:"",source:"",saved:new Set(),sort:"soonest",aiRanking:[],aiInsight:"",aiBusy:false};
const sourceColors={Luma:"#b9f451",Meetup:"#f487ff",Eventbrite:"#ffb45a",Community:"#53d7ff"};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function dateParts(date){const d=new Date(date+"T12:00:00");return {day:d.getDate(),month:d.toLocaleString("en",{month:"short"}).toUpperCase(),label:d.toLocaleDateString("en",{weekday:"short",month:"short",day:"numeric"})}}
function smartTerms(q){return q.toLowerCase().replace(/genai|generative ai/g,"ai").replace(/workshops?/g," ").split(/\s+/).filter(x=>x.length>2)}
function matches(e){const text=[e.title,e.venue,e.area,e.source,e.format,e.price,...e.topics].join(" ").toLowerCase();const q=state.query.toLowerCase(); const termPass=smartTerms(q).every(t=>text.includes(t)||({weekend:["2026-07-18","2026-07-19"].includes(e.date),free:e.price==="Free",hackathon:e.title.toLowerCase().includes("hack"),near:e.area.includes("Hitech")}[t]));const datePass=state.date==="all"||(state.date==="week"&&e.date<="2026-07-22")||(state.date==="weekend"&&["2026-07-18","2026-07-19"].includes(e.date));return termPass&&datePass&&(!state.format||e.format===state.format)&&(!state.topic||e.topics.includes(state.topic))&&(!state.source||e.source===state.source)}
function render(){let list=events.filter(matches);if(state.aiRanking.length)list.sort((a,b)=>state.aiRanking.indexOf(a.id)-state.aiRanking.indexOf(b.id));if(state.sort==="saved") list.sort((a,b)=>Number(state.saved.has(b.id))-Number(state.saved.has(a.id)));$("#eventTotal").textContent=list.length;$("#savedCount").textContent=state.saved.size;$("#feedTitle").textContent=state.query?`Results for “${state.query}”`:"Upcoming in Hyderabad";const insight=$("#aiInsight");if(state.query&&list.length){insight.hidden=false;insight.innerHTML=`<span>✦ ${state.aiBusy?"Finding the strongest signal…":state.aiInsight?"AI signal:":"Smart signal:"}</span> ${state.aiInsight||`Found ${list.length} Hyderabad event${list.length===1?"":"s"} matching your intent. Ranked by topic relevance, timing, and locality.`}`}else insight.hidden=true;$("#eventList").innerHTML=list.map(card).join("");$("#emptyState").hidden=!!list.length;$$('.save').forEach(b=>b.addEventListener('click',ev=>{ev.stopPropagation();toggleSave(+b.dataset.id)}));$$('.event-card').forEach(c=>c.addEventListener('click',()=>openEvent(+c.dataset.id)))}
function card(e){const d=dateParts(e.date),saved=state.saved.has(e.id);return `<article class="event-card" data-id="${e.id}" style="--source:${sourceColors[e.source]}"><div class="date-block"><div class="day">${d.day}</div><div class="month">${d.month}</div></div><div class="event-meta"><div class="source-row"><span class="source">${e.source}</span>${e.urgency?`<span class="urgency">${e.urgency}</span>`:""}</div><h3>${e.title}</h3><div class="details"><span>${e.time}</span><span>•</span><span>${e.venue}</span><span>•</span><span>${e.price}</span></div></div><div class="tags">${e.topics.map((t,i)=>`<span class="tag ${i===0?"primary":""}">${t}</span>`).join("")}<button class="save ${saved?"saved":""}" data-id="${e.id}" aria-label="Save event">${saved?"♥":"♡"}</button></div></article>`}
function toggleSave(id){state.saved.has(id)?state.saved.delete(id):state.saved.add(id);toast(state.saved.has(id)?"Saved to your radar":"Removed from saved events");render()}
function openEvent(id){const e=events.find(x=>x.id===id),d=dateParts(e.date);$("#dialogContent").innerHTML=`<div class="dialog-source">${e.source.toUpperCase()} · HYDERABAD</div><h2 class="dialog-title">${e.title}</h2><p class="dialog-info">${d.label} · ${e.time}<br>${e.venue}, ${e.area} · ${e.format} · ${e.price}</p><p class="dialog-summary"><strong>Why it surfaced:</strong> ${e.topics.join(" + ")} event in Hyderabad, extracted and normalized from ${e.source}. ${e.urgency||""}</p><div class="tags" style="justify-content:flex-start;max-width:none;margin-bottom:20px">${e.topics.map(t=>`<span class="tag primary">${t}</span>`).join("")}</div><div class="dialog-actions"><a class="register" href="${e.link}" target="_blank" rel="noreferrer">Open original listing ↗</a><button class="saved-button" onclick="toggleSave(${e.id})">${state.saved.has(e.id)?"♥ Saved":"♡ Save event"}</button></div>`;$("#eventDialog").showModal()}
function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),2200)}
async function aiSearch(){const query=state.query.trim();if(!query)return;state.aiBusy=true;state.aiInsight="";state.aiRanking=[];render();try{const response=await fetch('/api/ai-search',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,events})});if(!response.ok)throw new Error();const result=await response.json();state.aiRanking=result.ranked_ids||[];state.aiInsight=result.insight||"AI-ranked for your intent."}catch{state.aiInsight="Showing local smart matching while AI search is unavailable."}finally{state.aiBusy=false;render()}}
$("#query").addEventListener("input",e=>{state.query=e.target.value;state.aiRanking=[];state.aiInsight="";render()});$("#query").addEventListener("keydown",e=>{if(e.key==='Enter')aiSearch()});$("#searchButton").addEventListener("click",aiSearch);$$('.prompt-chip').forEach(b=>b.addEventListener('click',()=>{$("#query").value=b.textContent;state.query=b.textContent;aiSearch()}));$$('.filter-option').forEach(b=>b.addEventListener('click',()=>{const k=b.dataset.filter;state[k]=state[k]===b.dataset.value?(k==='date'?'all':''):b.dataset.value;$$(`[data-filter="${k}"]`).forEach(x=>x.classList.toggle('active',state[k]===x.dataset.value));render()}));$("#clearFilters").addEventListener('click',()=>{Object.assign(state,{date:'all',format:'',topic:'',source:'',query:'',aiRanking:[],aiInsight:''});$("#query").value='';$$('.filter-option').forEach(x=>x.classList.toggle('active',x.dataset.value==='all'));render()});$("#emptyReset").addEventListener('click',()=>$("#clearFilters").click());$("#closeDialog").addEventListener('click',()=>$("#eventDialog").close());$("#savedToggle").addEventListener('click',()=>{state.sort=state.sort==='saved'?'soonest':'saved';toast(state.sort==='saved'?'Saved events floated to the top':'Showing all events by date');render()});$("#sortButton").addEventListener('click',()=>{state.sort=state.sort==='soonest'?'saved':'soonest';$("#sortButton").innerHTML=state.sort==='soonest'?'Soonest <span>⌄</span>':'Saved first <span>⌄</span>';render()});render();
